version: '3.7'

services:
  profile-db:
    container_name: postg
    image: postgres:13-alpine
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dbb
    networks:
      - node-bridge-network

networks:
  socket-network:
  node-bridge-network:
    driver: bridge
volumes:
  socket-pgdata:
